### ISSUE TITLE
Eslint failed due to ecmascript issues

### ISSUE THREAD

**Issue by hariclerry** [hariclerry/mediawiki#15]
https://github.com/hariclerry/mediawiki/blob/5a1d4a2f2b28bb37ff3b8c90c4a6adc2fbfff050/tests/playwright/specs/wikipedia.js#L1-L13

Eslint seems not to work for the sample test created. I believe that one of the reasons is because the playwright uses Async/await which is part of ECMAScript 2017. Adding the below configuration to the .eslintrc.json file seems to solve the issues.

`  "env": {
    "node": true,
    "es6": true
  },

  "parserOptions": {
    "ecmaVersion": 8
  }
`
The above is my conclusion from the research I did. You can advise on how to proceed on this or if there are other ways to solve this issue.

**Comment by sovoid** [comment]
@hariclerry please extend the `.eslintrc.json` file in the project root and add Playwrights rule. This should fix the problem. As a reference you can look at puppeteers patch 

https://gerrit.wikimedia.org/r/c/mediawiki/core/+/602294

**Comment by hariclerry** [comment]
Noted @und3fined-v01d  and thanks for the reference.
