### ISSUE TITLE
Set up mediawiki-docker in CI.

### ISSUE THREAD

**Issue by hariclerry** [hariclerry/mediawiki#30]

**Comment by hariclerry** [comment]
CC: @vidhi-mody @und3fined-v01d  @zeljkofilipin

**Comment by hariclerry** [comment]
Hey all, I'm not quite sure about the scope of this issue. Some insights would be great!

**Comment by sovoid** [comment]
@hariclerry It's quite straightforward actually. We need to run Mediawiki-docker on Github CI just like we would locally.
