### ISSUE TITLE
Implement sample test using Playwright

### ISSUE THREAD

**Issue by sovoid** [hariclerry/mediawiki#5]
Implement a simple test in Playwright that opens Wikipedia

## TODO

- [ ] Implement the simplest possible test that opens Wikipedia homepage

**Comment by hariclerry** [comment]
Hey @und3fined-v01d, does this task requires the test to open the **https://www.wikipedia.org/** page, am I right? Asking to be sure.

**Comment by sovoid** [comment]
> 
> 
> Hey @und3fined-v01d, does this task requires the test to open the **https://www.wikipedia.org/** page, am I right? Asking to be sure.

@hariclerry yes that is correct
